version: '3.8'

services:
  devflow-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    container_name: devflow-monitor-dev
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./docs:/app/docs:ro
      # Persist database
      - devflow-data:/app/data
      # Mount config files
      - ./config:/app/config:ro
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/devflow.db
      - MCP_SERVER_PORT=3000
      - LOG_LEVEL=debug
      # Development specific
      - DEBUG=true
      - WATCH_MODE=true
    ports:
      - "3000:3000"  # MCP server
      - "9229:9229"  # Node.js debugger
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - devflow-network

  # Optional: Dashboard service
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devflow-dashboard
    depends_on:
      - devflow-monitor
    environment:
      - NODE_ENV=production
      - DASHBOARD_MODE=cli
      - MCP_SERVER_URL=http://devflow-monitor:3000
    command: ["npx", "tsx", "scripts/dashboard.ts", "cli", "--refresh", "2000"]
    networks:
      - devflow-network
    profiles:
      - dashboard

volumes:
  devflow-data:
    name: devflow-monitor-data

networks:
  devflow-network:
    name: devflow-monitor-network
    driver: bridge