"""
Analyzer Type Definitions.

This package contains type definitions for all analyzers including
stage analysis, methodology tracking, metrics collection, AI monitoring,
and bottleneck detection.
"""

from .stage import (
    CODING_SUB_STAGE_ORDER,
    STAGE_DESCRIPTIONS,
    STAGE_ORDER,
    CodingSubStage,
    DevelopmentStage,
    StageActivity,
    StageActivityIndicator,
    StageAnalysisResult,
    StageDetectionRule,
    StagePattern,
    StageProgress,
    StageTransition,
)
from .methodology import (
    AggregateInfo,
    BDDElement,
    BDDScenario,
    BDDStep,
    BoundedContextInfo,
    ContextRelationship,
    DDDContextMap,
    DDDPattern,
    DevelopmentMethodology,
    EDAEventFlow,
    EDAPattern,
    EventFlowEdge,
    EventInfo,
    HandlerInfo,
    MethodologyAnalysisResult,
    MethodologyDetection,
    MethodologyDetectionRule,
    MethodologyScore,
    MethodologyTrend,
    SagaInfo,
    TDDCycle,
    TDDCycleState,
)
from .metrics import (
    AggregationType,
    Bottleneck,
    BottleneckType,
    CollaborationMetrics,
    MetricAlert,
    MetricAlertType,
    MetricAnalysisResult,
    MetricConfig,
    MetricData,
    MetricDefinition,
    MetricFilter,
    MetricSummary,
    MetricType,
    MetricUnit,
    MetricValue,
    PerformanceMetrics,
    ProductivityMetrics,
    QualityMetrics,
    TimeRange,
    TrendDirection,
)
from .ai import (
    AICodeQualityAnalysis,
    AICodeQualityIssue,
    AICodeQualityMetrics,
    AICollaborationAnalysis,
    AIDetectionRule,
    AIEffectivenessMetrics,
    AIInteraction,
    AISession,
    AISuggestion,
    AISuggestionStatus,
    AITool,
    AIToolConfig,
    AIUsageDetection,
    AIUsagePattern,
    AIUsageType,
)

__all__ = [
    # Stage types
    "DevelopmentStage",
    "CodingSubStage",
    "StageTransition",
    "StageActivity",
    "StageActivityIndicator",
    "StageDetectionRule",
    "StagePattern",
    "StageAnalysisResult",
    "StageProgress",
    "STAGE_ORDER",
    "CODING_SUB_STAGE_ORDER",
    "STAGE_DESCRIPTIONS",
    # Methodology types
    "DevelopmentMethodology",
    "DDDPattern",
    "TDDCycle",
    "BDDElement",
    "EDAPattern",
    "MethodologyDetection",
    "MethodologyScore",
    "MethodologyAnalysisResult",
    "MethodologyTrend",
    "MethodologyDetectionRule",
    "TDDCycleState",
    "DDDContextMap",
    "BoundedContextInfo",
    "ContextRelationship",
    "AggregateInfo",
    "BDDScenario",
    "BDDStep",
    "EDAEventFlow",
    "EventInfo",
    "HandlerInfo",
    "SagaInfo",
    "EventFlowEdge",
    # Metrics types
    "MetricType",
    "MetricUnit",
    "TimeRange",
    "MetricValue",
    "MetricDefinition",
    "AggregationType",
    "MetricData",
    "MetricSummary",
    "TrendDirection",
    "ProductivityMetrics",
    "QualityMetrics",
    "PerformanceMetrics",
    "CollaborationMetrics",
    "Bottleneck",
    "BottleneckType",
    "MetricFilter",
    "MetricAnalysisResult",
    "MetricAlert",
    "MetricAlertType",
    "MetricConfig",
    # AI types
    "AITool",
    "AIUsageType",
    "AISuggestionStatus",
    "AIUsageDetection",
    "AISuggestion",
    "AISession",
    "AIInteraction",
    "AIEffectivenessMetrics",
    "AIUsagePattern",
    "AICodeQualityAnalysis",
    "AICodeQualityMetrics",
    "AICodeQualityIssue",
    "AICollaborationAnalysis",
    "AIDetectionRule",
    "AIToolConfig",
]
