"""
Event Types Module.

This module exports all event types, categories, severities,
and related models for the event system.
"""

from .base import (
    BaseEvent,
    EventBatch,
    EventCategory,
    EventFilter,
    EventHandler,
    EventMetadata,
    EventPublishOptions,
    EventSeverity,
    EventStatistics,
    EventSubscriptionOptions,
    EventTransformer,
)
from .file import (
    ChangedLines,
    FileChangeAction,
    FileChangeInfo,
    FileContext,
    FileContextType,
    FileEvent,
    FileEventBuilder,
    FileEventData,
    FileEventType,
    FileInfo,
    FileBatchContext,
    FileBatchEvent,
    FileBatchEventData,
    FileBatchSummary,
    GitStatus,
    is_file_batch_event,
    is_file_event,
)
from .git import (
    BranchType,
    CommitAnalysis,
    CommitFileChange,
    ConflictDetail,
    GitAuthor,
    GitBranchEventData,
    GitBranchInfo,
    GitCommitEventData,
    GitCommitInfo,
    GitConflictInfo,
    GitEvent,
    GitEventBuilder,
    GitEventType,
    GitRemoteInfo,
    GitSyncEventData,
    GitTagInfo,
    MergeInfo,
    TrackingInfo,
    is_git_branch_event,
    is_git_commit_event,
    is_git_event,
    is_git_sync_event,
)

__all__ = [
    # Base types
    "BaseEvent",
    "EventBatch",
    "EventCategory",
    "EventFilter",
    "EventHandler",
    "EventMetadata",
    "EventPublishOptions",
    "EventSeverity",
    "EventStatistics",
    "EventSubscriptionOptions",
    "EventTransformer",
    # File types
    "ChangedLines",
    "FileChangeAction",
    "FileChangeInfo",
    "FileContext",
    "FileContextType",
    "FileEvent",
    "FileEventBuilder",
    "FileEventData",
    "FileEventType",
    "FileInfo",
    "FileBatchContext",
    "FileBatchEvent",
    "FileBatchEventData",
    "FileBatchSummary",
    "GitStatus",
    "is_file_batch_event",
    "is_file_event",
    # Git types
    "BranchType",
    "CommitAnalysis",
    "CommitFileChange",
    "ConflictDetail",
    "GitAuthor",
    "GitBranchEventData",
    "GitBranchInfo",
    "GitCommitEventData",
    "GitCommitInfo",
    "GitConflictInfo",
    "GitEvent",
    "GitEventBuilder",
    "GitEventType",
    "GitRemoteInfo",
    "GitSyncEventData",
    "GitTagInfo",
    "MergeInfo",
    "TrackingInfo",
    "is_git_branch_event",
    "is_git_commit_event",
    "is_git_event",
    "is_git_sync_event",
]
