"""
AI Collaboration Monitor.

Tracks AI tool usage (Claude, Copilot, ChatGPT, etc.) and analyzes
effectiveness, patterns, and code quality impact.
"""

from __future__ import annotations

import hashlib
import re
from datetime import datetime
from typing import Any, Callable

from ..events.engine import EventEngine, get_event_engine
from ..events.types.base import BaseEvent, EventCategory
from ..events.types.file import FileChangeAction
from ..events.types.git import GitEventType
from .types.ai import (
    AICodeQualityAnalysis,
    AICodeQualityIssue,
    AICodeQualityMetrics,
    AICollaborationAnalysis,
    AIDetectionRule,
    AIEffectivenessMetrics,
    AIInteraction,
    AISession,
    AISuggestion,
    AISuggestionStatus,
    AITool,
    AIUsageDetection,
    AIUsagePattern,
    AIUsageType,
)


class AIMonitor:
    """
    AI collaboration monitor.

    Tracks AI tool usage and provides effectiveness analysis.
    """

    DETECTION_WINDOW = 3600000  # 1 hour in milliseconds
    SESSION_TIMEOUT = 300000  # 5 minutes in milliseconds

    def __init__(self, event_engine: EventEngine | None = None):
        """
        Initialize the AI monitor.

        Args:
            event_engine: Optional event engine instance.
        """
        self._event_engine = event_engine or get_event_engine()
        self._detections: list[AIUsageDetection] = []
        self._suggestions: dict[str, AISuggestion] = {}
        self._sessions: dict[str, AISession] = {}
        self._active_sessions: dict[AITool, AISession] = {}
        self._detection_rules: dict[AITool, AIDetectionRule] = {}
        self._listeners: dict[str, list[Callable]] = {}
        self._subscription_id: str | None = None

        self._initialize_detection_rules()

    def start(self) -> None:
        """Start the AI monitor and subscribe to events."""
        self._subscription_id = self._event_engine.subscribe(
            "*",
            self._handle_event,
        )

    def stop(self) -> None:
        """Stop the AI monitor."""
        if self._subscription_id:
            self._event_engine.unsubscribe(self._subscription_id)
            self._subscription_id = None

    def on(self, event_type: str, handler: Callable) -> None:
        """Register an event listener."""
        if event_type not in self._listeners:
            self._listeners[event_type] = []
        self._listeners[event_type].append(handler)

    def emit(self, event_type: str, *args: Any) -> None:
        """Emit an event to listeners."""
        if event_type in self._listeners:
            for handler in self._listeners[event_type]:
                try:
                    handler(*args)
                except Exception:
                    pass

    def _initialize_detection_rules(self) -> None:
        """Initialize AI tool detection rules."""
        # Claude detection rules
        self._detection_rules[AITool.CLAUDE] = AIDetectionRule(
            tool=AITool.CLAUDE,
            patterns={
                "comment": [
                    r"Generated by Claude",
                    r"Claude AI",
                    r"anthropic.*claude",
                ],
                "code": [
                    r"claude_api",
                    r"anthropic.*sdk",
                ],
                "file": [
                    r"\.claude/",
                    r"claude.*\.(md|txt|json)$",
                ],
                "process": [
                    r"claude",
                    r"anthropic",
                ],
            },
            confidence=0.8,
        )

        # GitHub Copilot detection rules
        self._detection_rules[AITool.GITHUB_COPILOT] = AIDetectionRule(
            tool=AITool.GITHUB_COPILOT,
            patterns={
                "comment": [
                    r"Copilot",
                    r"Generated by.*Copilot",
                    r"github\.copilot",
                ],
                "code": [
                    r"copilot",
                ],
                "file": [
                    r"\.copilot",
                    r"copilot.*\.json$",
                ],
                "process": [
                    r"copilot",
                    r"github.*copilot",
                ],
            },
            confidence=0.75,
        )

        # ChatGPT detection rules
        self._detection_rules[AITool.CHATGPT] = AIDetectionRule(
            tool=AITool.CHATGPT,
            patterns={
                "comment": [
                    r"ChatGPT",
                    r"Generated by.*ChatGPT",
                    r"OpenAI.*GPT",
                ],
                "code": [
                    r"openai.*api",
                    r"gpt-[34]",
                ],
                "file": [
                    r"\.openai",
                    r"chatgpt.*\.(md|txt|json)$",
                ],
                "process": [
                    r"chatgpt",
                    r"openai",
                ],
            },
            confidence=0.75,
        )

        # Cursor detection rules
        self._detection_rules[AITool.CURSOR] = AIDetectionRule(
            tool=AITool.CURSOR,
            patterns={
                "comment": [
                    r"Cursor",
                    r"Generated.*Cursor",
                ],
                "file": [
                    r"\.cursor",
                    r"cursor.*\.json$",
                ],
                "process": [
                    r"cursor",
                ],
            },
            confidence=0.7,
        )

        # TabNine detection rules
        self._detection_rules[AITool.TABNINE] = AIDetectionRule(
            tool=AITool.TABNINE,
            patterns={
                "comment": [
                    r"TabNine",
                    r"Tabnine",
                ],
                "file": [
                    r"\.tabnine",
                ],
                "process": [
                    r"tabnine",
                ],
            },
            confidence=0.7,
        )

        # CodeWhisperer detection rules
        self._detection_rules[AITool.CODEWHISPERER] = AIDetectionRule(
            tool=AITool.CODEWHISPERER,
            patterns={
                "comment": [
                    r"CodeWhisperer",
                    r"Amazon.*CodeWhisperer",
                ],
                "file": [
                    r"\.codewhisperer",
                ],
                "process": [
                    r"codewhisperer",
                ],
            },
            confidence=0.7,
        )

    async def _handle_event(self, event: BaseEvent) -> None:
        """Handle incoming events."""
        await self.analyze_event(event)

    async def analyze_event(self, event: BaseEvent) -> None:
        """
        Analyze an event for AI tool usage.

        Args:
            event: The event to analyze.
        """
        if event.category == EventCategory.FILE:
            await self._analyze_file_event(event)
        elif event.category == EventCategory.GIT:
            await self._analyze_git_event(event)
        elif event.category == EventCategory.PROCESS:
            await self._analyze_process_event(event)

        self._update_metrics()

    async def _analyze_file_event(self, event: BaseEvent) -> None:
        """Analyze file event for AI usage."""
        data = event.data
        action = data.get("action")
        if action not in (FileChangeAction.ADD.value, FileChangeAction.CHANGE.value):
            return

        new_file = data.get("new_file", {})
        file_path = new_file.get("path", "")
        if not file_path:
            return

        content = new_file.get("content", "")
        old_file = data.get("old_file", {})
        old_content = old_file.get("content", "") if old_file else ""

        for tool, rule in self._detection_rules.items():
            detection = self._detect_ai_usage(file_path, content, rule)
            if detection:
                self._add_detection(detection)

                # Track suggestion if content changed
                if old_content and content != old_content:
                    suggestion = self._track_suggestion(
                        tool,
                        file_path,
                        old_content,
                        content,
                        detection.usage_type,
                    )
                    if suggestion:
                        self.emit("suggestion_tracked", suggestion)

                # Update session
                self._update_session(tool, detection)

    async def _analyze_git_event(self, event: BaseEvent) -> None:
        """Analyze git event for AI usage."""
        if event.type == GitEventType.COMMIT_CREATED.value:
            commit = event.data.get("commit", {})
            message = commit.get("message", "")

            for tool, rule in self._detection_rules.items():
                comment_patterns = rule.patterns.get("comment", [])
                for pattern in comment_patterns:
                    if re.search(pattern, message, re.IGNORECASE):
                        detection = AIUsageDetection(
                            tool=tool,
                            usage_type=AIUsageType.CODE_GENERATION,
                            confidence=0.6,
                            context=f"Commit: {message}",
                        )
                        self._add_detection(detection)
                        break

    async def _analyze_process_event(self, event: BaseEvent) -> None:
        """Analyze process event for AI usage."""
        process_name = event.data.get("name", "")

        for tool, rule in self._detection_rules.items():
            process_patterns = rule.patterns.get("process", [])
            for pattern in process_patterns:
                if re.search(pattern, process_name, re.IGNORECASE):
                    detection = AIUsageDetection(
                        tool=tool,
                        usage_type=AIUsageType.OTHER,
                        confidence=0.7,
                        context=f"Process: {process_name}",
                    )
                    self._add_detection(detection)

                    # Start session if not active
                    if tool not in self._active_sessions:
                        self._start_session(tool)
                    break

    def _detect_ai_usage(
        self,
        file_path: str,
        content: str,
        rule: AIDetectionRule,
    ) -> AIUsageDetection | None:
        """Detect AI usage from file content."""
        confidence = 0.0
        evidence: list[str] = []
        usage_type = AIUsageType.OTHER

        # File pattern check
        file_patterns = rule.patterns.get("file", [])
        for pattern in file_patterns:
            if re.search(pattern, file_path, re.IGNORECASE):
                confidence += 0.3
                evidence.append(f"File path matches: {pattern}")
                break

        # Code pattern check
        code_patterns = rule.patterns.get("code", [])
        for pattern in code_patterns:
            if re.search(pattern, content, re.IGNORECASE):
                confidence += 0.4
                evidence.append(f"Code pattern found: {pattern}")
                usage_type = self._infer_usage_type(content)
                break

        # Comment pattern check
        comment_patterns = rule.patterns.get("comment", [])
        for pattern in comment_patterns:
            matches = re.search(pattern, content, re.IGNORECASE)
            if matches:
                confidence += 0.3
                evidence.append(f"Comment found: {matches.group(0)}")
                break

        if confidence < rule.confidence * 0.5:
            return None

        return AIUsageDetection(
            tool=rule.tool,
            usage_type=usage_type,
            file_path=file_path,
            confidence=min(confidence, 1.0),
            context=", ".join(evidence),
        )

    def _infer_usage_type(self, content: str) -> AIUsageType:
        """Infer usage type from content."""
        if re.search(r"test|spec|describe|it\(", content, re.IGNORECASE):
            return AIUsageType.TESTING
        if re.search(r"/\*\*|\*\s*@|README|docs/", content, re.IGNORECASE):
            return AIUsageType.DOCUMENTATION
        if re.search(r"refactor|improve|optimize", content, re.IGNORECASE):
            return AIUsageType.REFACTORING
        if re.search(r"fix|bug|error|debug", content, re.IGNORECASE):
            return AIUsageType.DEBUGGING
        if re.search(r"architecture|design|pattern|structure", content, re.IGNORECASE):
            return AIUsageType.ARCHITECTURE
        return AIUsageType.CODE_GENERATION

    def _track_suggestion(
        self,
        tool: AITool,
        file_path: str,
        original_code: str,
        suggested_code: str,
        usage_type: AIUsageType,
    ) -> AISuggestion:
        """Track an AI suggestion."""
        suggestion_id = self._generate_suggestion_id(tool, file_path)
        modification_ratio = self._calculate_modification_ratio(
            original_code, suggested_code
        )

        suggestion = AISuggestion(
            id=suggestion_id,
            tool=tool,
            usage_type=usage_type,
            status=AISuggestionStatus.ACCEPTED,
            file_path=file_path,
            original_code=original_code,
            suggested_code=suggested_code,
            accepted_code=suggested_code,
            modification_ratio=modification_ratio,
        )

        self._suggestions[suggestion_id] = suggestion

        # Analyze quality
        quality_analysis = self._analyze_code_quality(suggestion)
        self.emit("quality_analyzed", quality_analysis)

        return suggestion

    def _start_session(self, tool: AITool) -> None:
        """Start a new AI session."""
        session_id = self._generate_session_id(tool)
        session = AISession(
            id=session_id,
            tool=tool,
            start_time=datetime.utcnow(),
            interactions=[],
        )

        self._sessions[session_id] = session
        self._active_sessions[tool] = session
        self.emit("session_started", session)

    def _end_session(self, session_id: str) -> None:
        """End an AI session."""
        session = self._sessions.get(session_id)
        if not session or session.end_time:
            return

        session.end_time = datetime.utcnow()

        # Remove from active sessions
        active_session = self._active_sessions.get(session.tool)
        if active_session and active_session.id == session_id:
            del self._active_sessions[session.tool]

        self.emit("session_ended", session)

    def _update_session(
        self,
        tool: AITool,
        detection: AIUsageDetection,
    ) -> None:
        """Update session with new interaction."""
        session = self._active_sessions.get(tool)
        if not session:
            self._start_session(tool)
            session = self._active_sessions.get(tool)

        if not session:
            return

        interaction = AIInteraction(
            timestamp=detection.timestamp,
            type=detection.usage_type,
            prompt=detection.prompt,
            response=detection.suggestion,
        )

        session.interactions.append(interaction)

    def _calculate_modification_ratio(
        self,
        original: str,
        modified: str,
    ) -> float:
        """Calculate the ratio of modified lines."""
        if not original or not modified:
            return 1.0

        original_lines = original.split("\n")
        modified_lines = modified.split("\n")
        max_lines = max(len(original_lines), len(modified_lines))

        changed_lines = 0
        for i in range(max_lines):
            orig_line = original_lines[i] if i < len(original_lines) else ""
            mod_line = modified_lines[i] if i < len(modified_lines) else ""
            if orig_line != mod_line:
                changed_lines += 1

        return changed_lines / max_lines if max_lines > 0 else 0.0

    def _analyze_code_quality(
        self,
        suggestion: AISuggestion,
    ) -> AICodeQualityAnalysis:
        """Analyze the quality of AI-generated code."""
        code = suggestion.suggested_code

        quality = AICodeQualityMetrics(
            readability=self._assess_readability(code),
            maintainability=self._assess_maintainability(code),
            performance=self._assess_performance(code),
            security=self._assess_security(code),
            testability=self._assess_testability(code),
        )

        issues = self._detect_issues(code)
        improvements = self._suggest_improvements(code, quality)

        return AICodeQualityAnalysis(
            suggestion=suggestion,
            quality=quality,
            issues=issues,
            improvements=improvements,
        )

    def _assess_readability(self, code: str) -> int:
        """Assess code readability (0-100)."""
        score = 100
        lines = code.split("\n")

        # Long lines penalty
        long_lines = sum(1 for line in lines if len(line) > 120)
        score -= long_lines * 2

        # Complex expressions penalty
        complex_expr = len(re.findall(r"&&|\|\||[?:]", code))
        score -= min(complex_expr, 20)

        # Comment ratio
        comment_lines = sum(
            1 for line in lines
            if line.strip().startswith(("//", "/*", "*", "#"))
        )
        comment_ratio = comment_lines / len(lines) if lines else 0
        if comment_ratio < 0.1:
            score -= 10
        if comment_ratio > 0.3:
            score -= 5

        return max(0, score)

    def _assess_maintainability(self, code: str) -> int:
        """Assess code maintainability (0-100)."""
        score = 100

        # Function length
        functions = re.findall(r"function\s+\w+|const\s+\w+\s*=\s*(?:async\s*)?\(", code)
        if functions:
            avg_length = len(code) / len(functions)
            if avg_length > 500:
                score -= 20

        # Duplicate patterns
        duplicates = self._find_duplicate_patterns(code)
        score -= duplicates * 5

        # Modularity check
        imports = len(re.findall(r"import|require", code))
        exports = len(re.findall(r"export", code))
        if imports == 0 and exports == 0 and len(code) > 200:
            score -= 15

        return max(0, score)

    def _assess_performance(self, code: str) -> int:
        """Assess code performance (0-100)."""
        score = 100

        # Nested loops
        nested_loops = len(re.findall(r"for.*{[\s\S]*?for", code))
        score -= nested_loops * 10

        # Sync file operations
        sync_ops = len(re.findall(r"readFileSync|writeFileSync", code))
        score -= sync_ops * 5

        return max(0, score)

    def _assess_security(self, code: str) -> int:
        """Assess code security (0-100)."""
        score = 100

        # SQL injection risk
        if re.search(r"query.*\+|query.*\$\{", code):
            score -= 20

        # eval usage
        if re.search(r"eval\s*\(", code):
            score -= 30

        # Hardcoded passwords
        if re.search(r'password\s*=\s*["\'][\w]+["\']', code, re.IGNORECASE):
            score -= 25

        return max(0, score)

    def _assess_testability(self, code: str) -> int:
        """Assess code testability (0-100)."""
        score = 100

        # Side effects
        functions = len(re.findall(r"function|=>", code))
        side_effects = len(re.findall(r"console\.|document\.|window\.|process\.", code))
        if functions > 0:
            side_effect_ratio = side_effects / functions
            score -= int(side_effect_ratio * 20)

        # Hardcoded dependencies
        hardcoded_deps = len(re.findall(r"new\s+\w+\(", code))
        score -= hardcoded_deps * 2

        return max(0, score)

    def _find_duplicate_patterns(self, code: str) -> int:
        """Find duplicate patterns in code."""
        lines = [line for line in code.split("\n") if len(line.strip()) > 10]
        patterns: dict[str, int] = {}

        for i in range(len(lines) - 2):
            pattern = "\n".join(lines[i : i + 3])
            patterns[pattern] = patterns.get(pattern, 0) + 1

        return sum(1 for count in patterns.values() if count > 1)

    def _detect_issues(self, code: str) -> list[AICodeQualityIssue]:
        """Detect code quality issues."""
        issues: list[AICodeQualityIssue] = []

        # Loose equality
        if re.search(r"==(?!=)", code):
            issues.append(
                AICodeQualityIssue(
                    type="bug",
                    severity="medium",
                    description="Use === instead of == for comparison",
                )
            )

        # eval usage
        if re.search(r"eval\s*\(", code):
            issues.append(
                AICodeQualityIssue(
                    type="vulnerability",
                    severity="critical",
                    description="Avoid using eval() due to security risks",
                )
            )

        # TODO/FIXME
        if re.search(r"TODO|FIXME|HACK", code):
            issues.append(
                AICodeQualityIssue(
                    type="code_smell",
                    severity="low",
                    description="Unresolved TODO/FIXME comments found",
                )
            )

        # Triple nested loops
        if re.search(r"for.*{[\s\S]*?for.*{[\s\S]*?for", code):
            issues.append(
                AICodeQualityIssue(
                    type="performance",
                    severity="high",
                    description="Triple nested loops detected",
                )
            )

        return issues

    def _suggest_improvements(
        self,
        code: str,
        quality: AICodeQualityMetrics,
    ) -> list[str]:
        """Suggest code improvements."""
        improvements: list[str] = []

        if quality.readability < 70:
            improvements.append("Break down long lines and complex expressions")
            improvements.append("Add meaningful comments for complex logic")

        if quality.maintainability < 70:
            improvements.append("Split large functions into smaller, focused ones")
            improvements.append("Extract common patterns into reusable functions")

        if quality.performance < 70:
            improvements.append("Consider using async operations for I/O")
            improvements.append("Optimize nested loops with better algorithms")

        if quality.security < 70:
            improvements.append("Use parameterized queries to prevent SQL injection")
            improvements.append("Store sensitive data in environment variables")

        if quality.testability < 70:
            improvements.append("Use dependency injection for better testability")
            improvements.append("Separate business logic from side effects")

        return improvements

    def _add_detection(self, detection: AIUsageDetection) -> None:
        """Add an AI usage detection."""
        self._detections.append(detection)

        # Remove old detections
        cutoff_ms = datetime.utcnow().timestamp() * 1000 - self.DETECTION_WINDOW
        self._detections = [
            d for d in self._detections
            if d.timestamp.timestamp() * 1000 > cutoff_ms
        ]

        self.emit("ai_usage_detected", detection)

    def _update_metrics(self) -> None:
        """Update effectiveness metrics for all tools."""
        for tool in AITool:
            if tool != AITool.OTHER:
                metrics = self._calculate_metrics(tool)
                self.emit("metrics_updated", metrics)

    def _calculate_metrics(self, tool: AITool) -> AIEffectivenessMetrics:
        """Calculate effectiveness metrics for a tool."""
        cutoff_ms = datetime.utcnow().timestamp() * 1000 - self.DETECTION_WINDOW

        recent_suggestions = [
            s for s in self._suggestions.values()
            if s.tool == tool
            and s.timestamp.timestamp() * 1000 > cutoff_ms
        ]

        accepted = sum(
            1 for s in recent_suggestions
            if s.status == AISuggestionStatus.ACCEPTED
        )
        modified = sum(
            1 for s in recent_suggestions
            if s.status == AISuggestionStatus.MODIFIED
        )
        total = len(recent_suggestions)

        acceptance_rate = accepted / total if total > 0 else 0.0
        modification_rate = modified / total if total > 0 else 0.0

        response_times = [
            s.response_time for s in recent_suggestions
            if s.response_time is not None
        ]
        avg_response_time = (
            sum(response_times) // len(response_times)
            if response_times
            else 0
        )

        return AIEffectivenessMetrics(
            tool=tool,
            time_window="hour",
            acceptance_rate=acceptance_rate,
            modification_rate=modification_rate,
            average_response_time=avg_response_time,
            total_interactions=total,
            successful_interactions=accepted + modified,
            token_efficiency=0.7,  # Placeholder
            times_saved=total * 5,  # 5 minutes per interaction
            code_quality_impact={
                "bugs_introduced": 0,
                "bugs_fixed": sum(
                    1 for s in recent_suggestions
                    if s.usage_type == AIUsageType.DEBUGGING
                ),
                "complexity_change": 0,
                "test_coverage_change": 0,
            },
        )

    def analyze_usage_patterns(self) -> dict[AITool, AIUsagePattern]:
        """Analyze AI usage patterns."""
        patterns: dict[AITool, AIUsagePattern] = {}

        for tool in AITool:
            if tool == AITool.OTHER:
                continue

            tool_detections = [d for d in self._detections if d.tool == tool]
            if not tool_detections:
                continue

            # Most used types
            type_counts: dict[AIUsageType, int] = {}
            for d in tool_detections:
                type_counts[d.usage_type] = type_counts.get(d.usage_type, 0) + 1

            most_used_types = sorted(
                type_counts.keys(),
                key=lambda t: type_counts[t],
                reverse=True,
            )[:3]

            # Peak hours
            hour_counts: dict[int, int] = {}
            for d in tool_detections:
                hour = d.timestamp.hour
                hour_counts[hour] = hour_counts.get(hour, 0) + 1

            peak_hours = sorted(
                hour_counts.keys(),
                key=lambda h: hour_counts[h],
                reverse=True,
            )[:3]

            # Average session duration
            tool_sessions = [
                s for s in self._sessions.values()
                if s.tool == tool and s.end_time
            ]
            avg_duration = 0
            if tool_sessions:
                total_duration = sum(
                    (s.end_time - s.start_time).total_seconds() / 60
                    for s in tool_sessions
                    if s.end_time
                )
                avg_duration = total_duration / len(tool_sessions)

            # Preferred file types
            file_types = [
                d.file_path.split(".")[-1]
                for d in tool_detections
                if d.file_path
            ]
            type_freq: dict[str, int] = {}
            for ft in file_types:
                type_freq[ft] = type_freq.get(ft, 0) + 1
            preferred_file_types = sorted(
                type_freq.keys(),
                key=lambda t: type_freq[t],
                reverse=True,
            )[:5]

            patterns[tool] = AIUsagePattern(
                tool=tool,
                patterns={
                    "most_used_types": [t.value for t in most_used_types],
                    "peak_hours": peak_hours,
                    "average_session_duration": avg_duration,
                    "preferred_file_types": preferred_file_types,
                    "common_prompt_patterns": [],
                },
                productivity={
                    "lines_generated_per_hour": self._calculate_lines_per_hour(tool),
                    "functions_completed_per_day": self._calculate_functions_per_day(tool),
                    "tests_written_per_week": self._calculate_tests_per_week(tool),
                },
            )

            self.emit("pattern_identified", patterns[tool])

        return patterns

    def _calculate_lines_per_hour(self, tool: AITool) -> int:
        """Calculate lines generated per hour."""
        hour_ago = datetime.utcnow().timestamp() * 1000 - 3600000
        recent = [
            s for s in self._suggestions.values()
            if s.tool == tool and s.timestamp.timestamp() * 1000 > hour_ago
        ]
        return sum(len(s.suggested_code.split("\n")) for s in recent)

    def _calculate_functions_per_day(self, tool: AITool) -> int:
        """Calculate functions completed per day."""
        day_ago = datetime.utcnow().timestamp() * 1000 - 86400000
        recent = [
            s for s in self._suggestions.values()
            if s.tool == tool and s.timestamp.timestamp() * 1000 > day_ago
        ]
        return sum(
            len(re.findall(r"function\s+\w+|const\s+\w+\s*=\s*(?:async\s*)?\(", s.suggested_code))
            for s in recent
        )

    def _calculate_tests_per_week(self, tool: AITool) -> int:
        """Calculate tests written per week."""
        week_ago = datetime.utcnow().timestamp() * 1000 - 604800000
        recent = [
            s for s in self._suggestions.values()
            if s.tool == tool
            and s.timestamp.timestamp() * 1000 > week_ago
            and s.usage_type == AIUsageType.TESTING
        ]
        return sum(
            len(re.findall(r"test\s*\(|it\s*\(|describe\s*\(", s.suggested_code))
            for s in recent
        )

    def analyze(self) -> AICollaborationAnalysis:
        """
        Perform complete AI collaboration analysis.

        Returns:
            Complete analysis result.
        """
        patterns = self.analyze_usage_patterns()
        tools: dict[AITool, dict[str, Any]] = {}

        for tool, pattern in patterns.items():
            metrics = self._calculate_metrics(tool)
            tools[tool] = {
                "sessions": sum(
                    1 for s in self._sessions.values() if s.tool == tool
                ),
                "interactions": metrics.total_interactions,
                "acceptance_rate": metrics.acceptance_rate,
                "times_saved": metrics.times_saved,
                "preferred_usage_types": pattern.patterns.get("most_used_types", []),
            }

        # Overall metrics
        total_ai_time = sum(
            (s.end_time - s.start_time).total_seconds() / 60
            for s in self._sessions.values()
            if s.end_time
        )
        human_coding_time = total_ai_time * 2  # Estimate
        ai_contribution_ratio = (
            total_ai_time / (total_ai_time + human_coding_time)
            if total_ai_time + human_coding_time > 0
            else 0
        )
        productivity_gain = (
            (total_ai_time / human_coding_time) * 100
            if human_coding_time > 0
            else 0
        )

        # Most effective tool
        most_effective_tool = AITool.OTHER
        max_efficiency = 0.0
        for tool, data in tools.items():
            efficiency = data.get("acceptance_rate", 0) * data.get("interactions", 0)
            if efficiency > max_efficiency:
                max_efficiency = efficiency
                most_effective_tool = tool

        return AICollaborationAnalysis(
            timestamp=datetime.utcnow(),
            tools=tools,
            overall_metrics={
                "total_ai_assisted_time": total_ai_time,
                "human_coding_time": human_coding_time,
                "ai_contribution_ratio": ai_contribution_ratio,
                "productivity_gain": productivity_gain,
            },
            insights={
                "most_effective_tool": most_effective_tool.value,
                "best_use_cases": self._get_best_use_cases(),
                "improvement_areas": self._get_improvement_areas(),
                "recommendations": self._generate_recommendations(),
            },
            trends=self._calculate_hourly_trends(),
        )

    def _get_best_use_cases(self) -> list[str]:
        """Get the best use cases for AI tools."""
        usage_stats: dict[AIUsageType, dict[str, int]] = {}

        for suggestion in self._suggestions.values():
            if suggestion.usage_type not in usage_stats:
                usage_stats[suggestion.usage_type] = {"count": 0, "accepted": 0}
            usage_stats[suggestion.usage_type]["count"] += 1
            if suggestion.status == AISuggestionStatus.ACCEPTED:
                usage_stats[suggestion.usage_type]["accepted"] += 1

        effectiveness = [
            (
                t,
                stats["accepted"] / stats["count"] if stats["count"] > 0 else 0,
            )
            for t, stats in usage_stats.items()
        ]
        effectiveness.sort(key=lambda x: x[1], reverse=True)

        return [t.value for t, _ in effectiveness[:3]]

    def _get_improvement_areas(self) -> list[str]:
        """Get areas for improvement."""
        areas: list[str] = []

        # Low acceptance rate
        avg_acceptance = self._calculate_overall_acceptance_rate()
        if avg_acceptance < 0.5:
            areas.append("AI suggestion acceptance rate is low. Prompt improvement needed.")

        # High modification rate
        avg_modification = self._calculate_overall_modification_rate()
        if avg_modification > 0.3:
            areas.append("AI suggestions are frequently modified. Better context needed.")

        return areas

    def _generate_recommendations(self) -> list[str]:
        """Generate recommendations."""
        recommendations: list[str] = []

        if len(self._detections) < 10:
            recommendations.append(
                "Use AI tools more actively to improve productivity."
            )

        avg_quality = self._calculate_average_code_quality()
        if avg_quality < 70:
            recommendations.append(
                "Review AI-generated code more carefully for quality."
            )

        recommendations.append(
            "Always review AI-generated code for quality assurance."
        )
        recommendations.append(
            "Use different AI tools appropriately for different tasks."
        )

        return recommendations

    def _calculate_hourly_trends(self) -> dict[str, list[int]]:
        """Calculate hourly usage trends."""
        hours = 24
        adoption: list[int] = []
        quality: list[int] = []
        efficiency: list[int] = []

        now = datetime.utcnow().timestamp() * 1000

        for i in range(hours):
            hour_start = now - (hours - i) * 3600000
            hour_end = hour_start + 3600000

            hour_detections = [
                d for d in self._detections
                if hour_start <= d.timestamp.timestamp() * 1000 < hour_end
            ]
            adoption.append(len(hour_detections))

            hour_suggestions = [
                s for s in self._suggestions.values()
                if hour_start <= s.timestamp.timestamp() * 1000 < hour_end
            ]

            if hour_suggestions:
                avg_quality_score = sum(
                    self._analyze_code_quality(s).quality.readability
                    for s in hour_suggestions
                ) / len(hour_suggestions)
                quality.append(int(avg_quality_score))

                accept_rate = sum(
                    1 for s in hour_suggestions
                    if s.status == AISuggestionStatus.ACCEPTED
                ) / len(hour_suggestions)
                efficiency.append(int(accept_rate * 100))
            else:
                quality.append(0)
                efficiency.append(0)

        return {
            "adoption": adoption,
            "quality": quality,
            "efficiency": efficiency,
        }

    def _calculate_overall_acceptance_rate(self) -> float:
        """Calculate overall acceptance rate."""
        suggestions = list(self._suggestions.values())
        if not suggestions:
            return 0.0
        accepted = sum(
            1 for s in suggestions
            if s.status == AISuggestionStatus.ACCEPTED
        )
        return accepted / len(suggestions)

    def _calculate_overall_modification_rate(self) -> float:
        """Calculate overall modification rate."""
        suggestions = list(self._suggestions.values())
        if not suggestions:
            return 0.0
        modified = sum(
            1 for s in suggestions
            if s.status == AISuggestionStatus.MODIFIED
        )
        return modified / len(suggestions)

    def _calculate_average_code_quality(self) -> float:
        """Calculate average code quality."""
        suggestions = list(self._suggestions.values())
        if not suggestions:
            return 0.0

        total_quality = sum(
            (
                self._analyze_code_quality(s).quality.readability +
                self._analyze_code_quality(s).quality.maintainability +
                self._analyze_code_quality(s).quality.performance +
                self._analyze_code_quality(s).quality.security +
                self._analyze_code_quality(s).quality.testability
            ) / 5
            for s in suggestions
        )
        return total_quality / len(suggestions)

    def _generate_suggestion_id(self, tool: AITool, file_path: str) -> str:
        """Generate a unique suggestion ID."""
        data = f"{tool.value}-{file_path}-{datetime.utcnow().timestamp()}"
        return hashlib.md5(data.encode()).hexdigest()[:16]

    def _generate_session_id(self, tool: AITool) -> str:
        """Generate a unique session ID."""
        import random
        data = f"{tool.value}-{datetime.utcnow().timestamp()}-{random.random()}"
        return hashlib.md5(data.encode()).hexdigest()[:16]

    def track_suggestion(
        self,
        tool: AITool,
        status: AISuggestionStatus,
        code_diff: str,
    ) -> None:
        """
        Track an AI suggestion.

        Args:
            tool: The AI tool used.
            status: Suggestion status (accepted/rejected/modified).
            code_diff: The code difference.
        """
        suggestion_id = self._generate_suggestion_id(tool, "manual")
        suggestion = AISuggestion(
            id=suggestion_id,
            tool=tool,
            usage_type=AIUsageType.CODE_GENERATION,
            status=status,
            file_path="manual",
            suggested_code=code_diff,
        )
        self._suggestions[suggestion_id] = suggestion
        self.emit("suggestion_tracked", suggestion)

    def get_ai_stats(self) -> dict[str, Any]:
        """
        Get AI usage statistics.

        Returns:
            Dictionary with AI usage statistics.
        """
        return {
            "total_detections": len(self._detections),
            "total_suggestions": len(self._suggestions),
            "total_sessions": len(self._sessions),
            "active_sessions": len(self._active_sessions),
            "tools_detected": list(set(d.tool.value for d in self._detections)),
            "acceptance_rate": self._calculate_overall_acceptance_rate(),
            "modification_rate": self._calculate_overall_modification_rate(),
            "average_quality": self._calculate_average_code_quality(),
        }


# Singleton instance
_ai_monitor: AIMonitor | None = None


def get_ai_monitor() -> AIMonitor:
    """Get the singleton AI monitor instance."""
    global _ai_monitor
    if _ai_monitor is None:
        _ai_monitor = AIMonitor()
    return _ai_monitor
